/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Color; // Untuk warna saldo
import java.text.NumberFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel; // Untuk JList

// --- Impor untuk CSV ---
import java.text.SimpleDateFormat; // Untuk format tanggal
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException; // Untuk parse date/double dari CSV
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.ArrayList; // Untuk menampung data impor
/**
 *
 * @author LENOVO
 */
public class AplikasiKeuangan extends javax.swing.JFrame {
// --- DATA & LOGIC (Koneksi ke Model) ---
private TransaksiDAO dao;
private Transaksi transaksiTerpilih; // Menyimpan transaksi yang sedang diklik
private NumberFormat formatRupiah;
private SimpleDateFormat formatDate; // Ditambahkan untuk CSV

// Variabel untuk menyimpan data JList
private javax.swing.DefaultListModel<Transaksi> listModel;
    /**
     * Creates new form AplikasiKeuangan
     */
    public AplikasiKeuangan() {
        initComponents();
         // --- Inisialisasi Logika ---
    this.dao = new TransaksiListDAO(); // Menggunakan implementasi ArrayList
    this.formatRupiah = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
    this.formatDate = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss"); // Format untuk CSV
    this.transaksiTerpilih = null;
    
    // --- Setup JList ---
    this.listModel = new DefaultListModel<>();
    listTransaksi.setModel(listModel);
    
    // Tambahkan listener untuk JList
    tambahkanListListener();
    
    // Muat data pertama kali
    refreshUI();
    }
    private void refreshUI() {
    // 1. Kosongkan list model
    listModel.clear();

    // 2. Dapatkan semua data dari DAO
    List<Transaksi> daftarTransaksi = dao.getAll();
    double totalSaldo = 0;

    // 3. Masukkan data ke JList dan hitung saldo
    for (Transaksi tx : daftarTransaksi) {
        // JList akan otomatis memanggil tx.toString()
        listModel.addElement(tx); 
        
        if (tx.getTipe() == TipeTransaksi.PEMASUKAN) {
            totalSaldo += tx.getJumlah();
        } else {
            totalSaldo -= tx.getJumlah();
        }
    }

    // 4. Update label total saldo di header
    lblTotalSaldo.setText(formatRupiah.format(totalSaldo));
    if (totalSaldo < 0) {
        lblTotalSaldo.setForeground(Color.RED);
    } else {
        lblTotalSaldo.setForeground(Color.BLACK); 
    }
}

/**
 * Membersihkan form input dan mengembalikan ke state default
 */
private void bersihkanForm() {
    transaksiTerpilih = null;
    txtDeskripsi.setText("");
    txtJumlah.setText("");
    radioPemasukan.setSelected(true);
    listTransaksi.clearSelection(); // Hapus seleksi di list
    
    btnTambah.setEnabled(true);
    btnUbah.setEnabled(false);
    btnHapus.setEnabled(false);
}

/**
 * Mengisi form berdasarkan data dari JList yang diklik
 */
private void pilihTransaksiDariList() {
    // Dapatkan OBJEK Transaksi yang dipilih dari JList
    transaksiTerpilih = listTransaksi.getSelectedValue(); 
    
    if (transaksiTerpilih == null) {
        bersihkanForm();
        return;
    }

    // Isi form dengan data
        txtDeskripsi.setText(transaksiTerpilih.getDeskripsi());
    txtJumlah.setText(String.valueOf(transaksiTerpilih.getJumlah()));
    if (transaksiTerpilih.getTipe() == TipeTransaksi.PEMASUKAN) {
        radioPemasukan.setSelected(true);
    } else {
        radioPengeluaran.setSelected(true);
    }

    // Atur state tombol
    btnTambah.setEnabled(false);
    btnUbah.setEnabled(true);
    btnHapus.setEnabled(true);
}

/**
 * Method untuk listener JList (dibuat manual)
 */
private void tambahkanListListener() {
    listTransaksi.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
        public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
            // Pastikan event selesai (tidak sedang adjust)
            if (!evt.getValueIsAdjusting()) {
                pilihTransaksiDariList();
            }
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTotalSaldo = new javax.swing.JLabel();
        btnEkspor = new javax.swing.JButton();
        btnImpor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTransaksi = new javax.swing.JList<>();
        panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        radioPemasukan = new javax.swing.JRadioButton();
        radioPengeluaran = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBersihkan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Dompet Saya");

        lblTotalSaldo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btnEkspor.setText("EKSPOR");
        btnEkspor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEksporActionPerformed(evt);
            }
        });

        btnImpor.setText("IMPORT");
        btnImpor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImporActionPerformed(evt);
            }
        });

        listTransaksi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jScrollPane1.setViewportView(listTransaksi);

        jLabel2.setText("Tipe Transaksi :");

        buttonGroup1.add(radioPemasukan);
        radioPemasukan.setText("Pemasukan");

        buttonGroup1.add(radioPengeluaran);
        radioPengeluaran.setText("Pengeluaran");

        jLabel3.setText("Deskripsi :");

        txtDeskripsi.setColumns(20);
        txtDeskripsi.setRows(5);
        jScrollPane2.setViewportView(txtDeskripsi);

        jLabel4.setText("Jumlah :");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBersihkan.setText("Bersihkan");
        btnBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihkanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(radioPemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(radioPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtJumlah)
                        .addGroup(panelLayout.createSequentialGroup()
                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioPemasukan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioPengeluaran)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnBersihkan))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnEkspor)
                        .addGap(32, 32, 32)
                        .addComponent(btnImpor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalSaldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEkspor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImpor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
       try {
        String deskripsi = txtDeskripsi.getText();
        double jumlah = Double.parseDouble(txtJumlah.getText());
        TipeTransaksi tipe = radioPemasukan.isSelected() ? TipeTransaksi.PEMASUKAN : TipeTransaksi.PENGELUARAN;
        Date tanggal = new Date(); // Tanggal hari ini

        if (deskripsi.isEmpty() || jumlah <= 0) {
            JOptionPane.showMessageDialog(this, "Deskripsi tidak boleh kosong dan Jumlah harus > 0.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Transaksi tx = new Transaksi(null, deskripsi, jumlah, tipe, tanggal);
        dao.tambah(tx);

        refreshUI();
        bersihkanForm();
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka yang valid.", "Error", JOptionPane.ERROR_MESSAGE);
    }  // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
            if (transaksiTerpilih == null) {
            JOptionPane.showMessageDialog(this, "Pilih transaksi yang ingin diubah.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Ambil data baru dari form
            String deskripsi = txtDeskripsi.getText();
            double jumlah = Double.parseDouble(txtJumlah.getText());
            TipeTransaksi tipe = radioPemasukan.isSelected() ? TipeTransaksi.PEMASUKAN : TipeTransaksi.PENGELUARAN;

            if (deskripsi.isEmpty() || jumlah <= 0) {
                JOptionPane.showMessageDialog(this, "Deskripsi tidak boleh kosong dan Jumlah harus > 0.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Update data di objek yang terpilih
            transaksiTerpilih.setDeskripsi(deskripsi);
            transaksiTerpilih.setJumlah(jumlah);
            transaksiTerpilih.setTipe(tipe);

            dao.ubah(transaksiTerpilih); // Kirim objek yang sudah diupdate ke DAO

            refreshUI();
            bersihkanForm();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka yang valid.", "Error", JOptionPane.ERROR_MESSAGE);
        }      // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        if (transaksiTerpilih == null) {
                JOptionPane.showMessageDialog(this, "Pilih transaksi yang ingin dihapus.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int konfirmasi = JOptionPane.showConfirmDialog(
                this,
                "Anda yakin ingin menghapus: " + transaksiTerpilih.getDeskripsi() + "?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION
            );

            if (konfirmasi == JOptionPane.YES_OPTION) {
                dao.hapus(transaksiTerpilih.getId());
                refreshUI();
                bersihkanForm();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihkanActionPerformed
        bersihkanForm();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBersihkanActionPerformed

    private void btnEksporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEksporActionPerformed
        JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Simpan sebagai CSV");
            fileChooser.setFileFilter(new FileNameExtensionFilter("CSV File", "csv"));

            int userSelection = fileChooser.showSaveDialog(this);

            if (userSelection == JFileChooser.APPROVE_OPTION) {
                File fileToSave = fileChooser.getSelectedFile();
                // Pastikan file memiliki ekstensi .csv
                if (!fileToSave.getAbsolutePath().endsWith(".csv")) {
                    fileToSave = new File(fileToSave.getAbsolutePath() + ".csv");
                }

                try (FileWriter writer = new FileWriter(fileToSave)) {
                    // Tulis Header CSV
                    writer.append("ID,Deskripsi,Jumlah,Tipe,Tanggal(ISO)\n");

                    // Tulis data
                    List<Transaksi> semuaData = dao.getAll(); // Ambil semua data
                    for (Transaksi tx : semuaData) {
                        writer.append(tx.getId()).append(",");
                        // Handle jika deskripsi mengandung koma (CSV standar)
                        writer.append("\"").append(tx.getDeskripsi().replace("\"", "\"\"")).append("\"").append(","); 
                        writer.append(String.valueOf(tx.getJumlah())).append(",");
                        writer.append(tx.getTipe().name()).append(",");
                        writer.append(formatDate.format(tx.getTanggal())); // Format ISO
                        writer.append("\n");
                    }
                    writer.flush();
                    JOptionPane.showMessageDialog(this, "Data berhasil diekspor ke " + fileToSave.getName(), "Sukses", JOptionPane.INFORMATION_MESSAGE);
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, "Gagal menyimpan file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }        // TODO add your handling code here:
    }//GEN-LAST:event_btnEksporActionPerformed

    private void btnImporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImporActionPerformed
        JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Pilih File CSV untuk Impor");
            fileChooser.setFileFilter(new FileNameExtensionFilter("CSV File", "csv"));

            int userSelection = fileChooser.showOpenDialog(this);

            if (userSelection == JFileChooser.APPROVE_OPTION) {
                File fileToOpen = fileChooser.getSelectedFile();

                int konfirmasi = JOptionPane.showConfirmDialog(this, 
                    "Impor file akan menghapus semua data saat ini. Lanjutkan?", 
                    "Konfirmasi Impor", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.WARNING_MESSAGE);

                if (konfirmasi != JOptionPane.YES_OPTION) {
                    return;
                }

                List<Transaksi> dataBaru = new ArrayList<>();
                try (BufferedReader reader = new BufferedReader(new FileReader(fileToOpen))) {
                    String line = reader.readLine(); // Baca header, abaikan

                    if (line == null || !line.startsWith("ID,Deskripsi")) {
                         JOptionPane.showMessageDialog(this, "Format file CSV tidak valid.", "Error", JOptionPane.ERROR_MESSAGE);
                         return;
                    }

                    while ((line = reader.readLine()) != null) {
                        // Regex sederhana untuk memecah CSV
                        String[] parts = line.split(",(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)", -1);

                        if (parts.length >= 5) {
                            String id = parts[0];
                            String deskripsi = parts[1].replace("\"", ""); // Hapus tanda kutip
                            double jumlah = Double.parseDouble(parts[2]);
                            TipeTransaksi tipe = TipeTransaksi.valueOf(parts[3]);
                            Date tanggal = formatDate.parse(parts[4]); // Parse dari format ISO

                            dataBaru.add(new Transaksi(id, deskripsi, jumlah, tipe, tanggal));
                        }
                    }

                    dao.setAll(dataBaru); // Timpa data di DAO
                    refreshUI(); // Segarkan UI
                    bersihkanForm();
                    JOptionPane.showMessageDialog(this, "Data berhasil diimpor.", "Sukses", JOptionPane.INFORMATION_MESSAGE);

                } catch (IOException | ParseException | IllegalArgumentException e) {
                    e.printStackTrace(); // Tampilkan error di console
                    JOptionPane.showMessageDialog(this, "Gagal membaca file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }        // TODO add your handling code here:
    }//GEN-LAST:event_btnImporActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiKeuangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBersihkan;
    private javax.swing.JButton btnEkspor;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnImpor;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTotalSaldo;
    private javax.swing.JList<Transaksi> listTransaksi;
    private javax.swing.JPanel panel;
    private javax.swing.JRadioButton radioPemasukan;
    private javax.swing.JRadioButton radioPengeluaran;
    private javax.swing.JTextArea txtDeskripsi;
    private javax.swing.JTextField txtJumlah;
    // End of variables declaration//GEN-END:variables
}
